#pragma once
struct ToAccIdEl;
struct WartEl;
struct AmountEl;
struct OriginAccIdEl;
struct CancelPinNonceEl;
struct PinNonceEl;
struct CompactFeeEl;
struct TokenSupplyEl;
struct TokenPrecisionEl;
struct TokenNameEl;
struct SignatureEl;
struct LimitPriceEl;
struct BuyEl;
