#pragma once
struct ToAccIdEl;
struct WartEl;
struct QuoteEl;
struct AmountEl;
struct SharesEl;
struct BaseEl;
struct OriginAccIdEl;
struct CancelNonceEl;
struct CancelHeightEl;
struct PinNonceEl;
struct CompactFeeEl;
struct AssetSupplyEl;
struct AssetPrecisionEl;
struct AssetNameEl;
struct SignatureEl;
struct LimitPriceEl;
struct BuyEl;
