/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "wart-wallet"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "wart-wallet"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION VERSION
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  const char *create_help; /**< @brief Create new wallet help description.  */
  char * restore_arg;	/**< @brief Restore wallet from private key.  */
  char * restore_orig;	/**< @brief Restore wallet from private key original value given at command line.  */
  const char *restore_help; /**< @brief Restore wallet from private key help description.  */
  const char *print_only_help; /**< @brief Do not save generated/restored wallet to disk but print result instead help description.  */
  char * file_arg;	/**< @brief Specify wallet file (default='wallet.json').  */
  char * file_orig;	/**< @brief Specify wallet file original value given at command line.  */
  const char *file_help; /**< @brief Specify wallet file help description.  */
  const char *address_help; /**< @brief Print wallet address help description.  */
  const char *balance_help; /**< @brief Print wallet balance help description.  */
  const char *send_help; /**< @brief Create send transaction help description.  */
  char * to_arg;	/**< @brief Specify transaction receipent address.  */
  char * to_orig;	/**< @brief Specify transaction receipent address original value given at command line.  */
  const char *to_help; /**< @brief Specify transaction receipent address help description.  */
  char * amount_arg;	/**< @brief Specify transaction amount.  */
  char * amount_orig;	/**< @brief Specify transaction amount original value given at command line.  */
  const char *amount_help; /**< @brief Specify transaction amount help description.  */
  char * fee_arg;	/**< @brief Specify transaction fee.  */
  char * fee_orig;	/**< @brief Specify transaction fee original value given at command line.  */
  const char *fee_help; /**< @brief Specify transaction fee help description.  */
  #if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
  long long int nonce_arg;	/**< @brief Specify transaction nonce.  */
  #else
  long nonce_arg;	/**< @brief Specify transaction nonce.  */
  #endif
  char * nonce_orig;	/**< @brief Specify transaction nonce original value given at command line.  */
  const char *nonce_help; /**< @brief Specify transaction nonce help description.  */
  char * host_arg;	/**< @brief Host (RPC-Node) (default='localhost').  */
  char * host_orig;	/**< @brief Host (RPC-Node) original value given at command line.  */
  const char *host_help; /**< @brief Host (RPC-Node) help description.  */
  int port_arg;	/**< @brief Port (RPC-Node) (default='3000').  */
  char * port_orig;	/**< @brief Port (RPC-Node) original value given at command line.  */
  const char *port_help; /**< @brief Port (RPC-Node) help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int create_given ;	/**< @brief Whether create was given.  */
  unsigned int restore_given ;	/**< @brief Whether restore was given.  */
  unsigned int print_only_given ;	/**< @brief Whether print-only was given.  */
  unsigned int file_given ;	/**< @brief Whether file was given.  */
  unsigned int address_given ;	/**< @brief Whether address was given.  */
  unsigned int balance_given ;	/**< @brief Whether balance was given.  */
  unsigned int send_given ;	/**< @brief Whether send was given.  */
  unsigned int to_given ;	/**< @brief Whether to was given.  */
  unsigned int amount_given ;	/**< @brief Whether amount was given.  */
  unsigned int fee_given ;	/**< @brief Whether fee was given.  */
  unsigned int nonce_given ;	/**< @brief Whether nonce was given.  */
  unsigned int host_given ;	/**< @brief Whether host was given.  */
  unsigned int port_given ;	/**< @brief Whether port was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
